### ISSUE TITLE
App build

### ISSUE THREAD

**Issue by AKprisonER** [archos-sa/aos-AVP#4]
Does this source cannot be built directly in Android studio ?
Does it need Full Android OS setup ?

**Comment by AKprisonER** [comment]
Does this need compulsory Repo tool for building this app ?
HOw normal users can build this app ?
Repo tool size itself will eat our Hard disk

**Comment by AlexRouxDanzi** [comment]
No you only need android sdk + ndk + all the usual to build the apk
Our make script should download everything it needs
It requires something like 13,5GB on my computer

**Comment by AKprisonER** [comment]
between https://github.com/archos-sa/aos-AVP  this won't be availble for import in Android studio.
SO how to import this project and build ?

**Comment by courville** [comment]
You can either build following the instructions in the Readme.md
Note that repo is a must to retrieve all the source code.
```
mkdir aos; cd aos
repo init -u https://github.com/archos-sa/aos-AVP
repo sync -j4
make
````
I use the following since I am not using a Linux based OS:
```
cd Video
./gradlew assembleCommunityLeanbackNoamazonPrivlibs
```
Once you've have done the repo sync you can also open the Video directory project and get it built via Android studio.

**Comment by AKprisonER** [comment]
Will try it out.. And individuals like me will have difficult in building becoz of Repo tool size from Android
Thanks
