### ISSUE TITLE
Audio Passthrough Issues

### ISSUE THREAD

**Issue by scottreed** [archos-sa/aos-AVP#8]
I have some problems with audio passthrough which have used to be fine in Archos but have been present since Version 8 and are in Nova for me too.

Mode 1 - This mode just plays static broken sound for me, this has been before the version 8 issue but was using mode 2

Mode 2 - Since upgrading to Shield Experience on Android 8 I've had problems. If I close the app and open fresh this mode works perfectly. But if I stop the video or try to play another one the next video looses sound and plays at twice the speed. What I do find is if I leave the video to fully finish and wait a while it's often okay. Nostalgia wise this is similar to an issue when I used to run Serviio on my PC and the application wasn't coding mpeg encoding processes correctly.

Currently I'm having to restart my app all the time would super love if anyone could take a look

**Comment by courville** [comment]
Thanks for reporting, strangely enough I do not reproduce on nvidia shield tv.
Would you be able to get logs (logcat) when the issue happens?
Another question: do you have "system sounds" enabled (i.e. bip at each remote key pressed)? If so please disable it in shield settings.
If you have any specific shield advanced sound settings please also report these so that we can align in order to reproduce.

**Comment by courville** [comment]
Just for internal reference: https://www.reddit.com/r/ShieldAndroidTV/comments/6fjktx/nvidia_shield_2017_no_sound_through_hdmi/

**Comment by scottreed** [comment]
I'll have a play with my system settings tomorrow and the other bits I have set up and settings wise. See if there's a way round it else I'll document all my settings. I've not used Logcat, does this require me compiling the source with the log options or is there any way of turning on logging flags or pulling the logs via a file browser or something? I'm a developer with a bit of Ionic experience and have built a few basic Android apps but my work focus in .NET and web technologies.

**Comment by courville** [comment]
In order to take logs you need to install adb on your PC and then enabled adb debug on the nvidia shield (https://sites.google.com/site/nvidiashieldtvutilityapp/home/enable-debugging).
There are some references around that can help you achieve this goal e.g. https://forums.geforce.com/default/topic/992035/shield-tv/nvidia-shield-best-of-forum-apps-tutorials-4k-hdr-logcat-root-bugs/
Good luck

**Comment by scottreed** [comment]
Hi thanks, I managed to get mode 1 working by disabling Stereo Upmix in the shield settings, this is now correctly passing through audio and I'm not getting the issues anymore. I tried with mode 2 changing every setting on the shield around the audio but it kept happening but as I've got mode 1 to work I'm happy to close. Thanks for the suggestions
